# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65\x63ho_msg.proto\"\x1c\n\x0bValueNumber\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1e\n\x0cVectorNumber\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\tEchoReply\x12\x10\n\x08rmessage\x18\x01 \x01(\t2S\n\x04\x45\x63ho\x12%\n\x07SayEcho\x12\x0c.EchoRequest\x1a\n.EchoReply\"\x00\x12$\n\x03Sum\x12\r.VectorNumber\x1a\x0c.ValueNumber\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUENUMBER._serialized_start=18
  _VALUENUMBER._serialized_end=46
  _VECTORNUMBER._serialized_start=48
  _VECTORNUMBER._serialized_end=78
  _ECHOREQUEST._serialized_start=80
  _ECHOREQUEST._serialized_end=110
  _ECHOREPLY._serialized_start=112
  _ECHOREPLY._serialized_end=141
  _ECHO._serialized_start=143
  _ECHO._serialized_end=226
# @@protoc_insertion_point(module_scope)
